---
- name: Clean up old snapshots on Proxmox VMs
  hosts: proxmox
  gather_facts: false
  tasks:
    - name: Get list of VMs from Proxmox
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        validate_certs: no
        state: info
      register: vm_list

    - name: Check and remove snapshots older than 2 days
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        validate_certs: no
        vmid: "{{ item.vmid }}"
        state: snapshot_info
      loop: "{{ vm_list.vms }}"
      register: snapshot_info

    - name: Remove snapshots older than 2 days
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        validate_certs: no
        vmid: "{{ item.0.vmid }}"
        snapshot: "{{ item.1.name }}"
        state: absent
      loop: "{{ snapshot_info.results | subelements('snapshots') }}"
      when: (ansible_date_time.iso8601 | to_datetime) - (item.1.date | to_datetime) > 2 * 24 * 3600
