---
- name: Usuwanie starych snapshotów w Proxmox
  hosts: proxmox
  gather_facts: yes  # Włącz zbieranie faktów
  vars:
    days_threshold: 5  # Liczba dni, po której snapshoty mają być usuwane

  tasks:
    - name: Pobierz listę wszystkich VM-ID
      shell: "qm list | awk 'NR>1 {print $1}'"
      register: vm_id_list
      changed_when: false

    - name: Pobierz listę snapshotów dla każdej maszyny
      shell: "qm listsnapshot {{ item }}"
      loop: "{{ vm_id_list.stdout_lines }}"
      register: snapshot_list
      changed_when: false

    - name: Filtruj snapshoty starsze niż {{ days_threshold }} dni
      set_fact:
        old_snapshots: "{{ old_snapshots | default([]) + [{'vm_id': item.item, 'snapshot': snap[0]}] }}"
      loop: "{{ snapshot_list.results | selectattr('stdout', 'defined') | map(attribute='stdout_lines') | list }}"
      vars:
        current_time: "{{ ansible_date_time.epoch | int }}"
      when: >
        item is defined and
        item | length > 0 and
        (current_time - (item[1] | int)) / 86400 > days_threshold

    - name: Usuń stare snapshoty
      shell: "qm delsnapshot {{ item.vm_id }} {{ item.snapshot }}"
      loop: "{{ old_snapshots }}"
      when: old_snapshots | length > 0
      register: deleted_snapshots

    - name: Wyświetl usunięte snapshoty
      debug:
        var: deleted_snapshots.results
