---
- name: Usuwanie starych snapshotów w Proxmox
  hosts: proxmox
  gather_facts: yes
  vars:
    days_threshold: 5  # Liczba dni, po której snapshoty mają być usuwane
    old_snapshots: []  # Inicjalizacja zmiennej old_snapshots

  tasks:
    - name: Pobierz listę wszystkich VM-ID
      shell: "qm list | awk 'NR>1 {print $1}'"
      register: vm_id_list
      changed_when: false

    - name: Pobierz listę snapshotów dla każdej maszyny
      shell: "qm listsnapshot {{ item }}"
      loop: "{{ vm_id_list.stdout_lines }}"
      register: snapshot_list
      changed_when: false

    - name: Debuguj snapshoty
      debug:
        var: snapshot_list.results

    - name: Filtruj snapshoty starsze niż {{ days_threshold }} dni
      set_fact:
        old_snapshots: "{{ old_snapshots + [{'vm_id': item.item, 'snapshot': item.stdout_lines[0].split()[0]}] }}"
      loop: "{{ snapshot_list.results }}"
      vars:
        current_time: "{{ ansible_date_time.epoch | int }}"
      when: >
        item.stdout_lines is defined and
        item.stdout_lines | length > 1 and
        item.stdout_lines[0].split()[1] is defined and
        (current_time - (item.stdout_lines[0].split()[1] | to_datetime('%Y-%m-%d %H:%M:%S') | to_timestamp)) > (days_threshold * 86400)

    - name: Usuń stare snapshoty
      shell: "qm delsnapshot {{ item.vm_id }} {{ item.snapshot }}"
      loop: "{{ old_snapshots }}"
      when: old_snapshots | length > 0
      register: deleted_snapshots

    - name: Wyświetl usunięte snapshoty
      debug:
        var: deleted_snapshots.results
