---
- name: Snapshot, update, restart, and clean snapshot on Proxmox VM
  hosts: all
  become: true
  gather_facts: true

  vars:
    vm_id: "{{ vm_id }}"  # ID maszyny wirtualnej w Proxmox
    snapshot_name: "snapshot_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"

  tasks:
    - name: Create snapshot with current date and time on Proxmox
      shell: |
        qm snapshot {{ vm_id }} --name "{{ snapshot_name }}" --description "Snapshot taken on {{ ansible_date_time.date }} {{ ansible_date_time.time }}"
      register: snapshot_result
      ignore_errors: true

    - name: Display snapshot creation result
      debug:
        msg: "Snapshot creation result: {{ snapshot_result }}"

    - name: Update the Debian system
      apt:
        update_cache: yes
        upgrade: dist
      when: "'0' in snapshot_result.rc"

    - name: Reboot the machine if updates were applied
      reboot:
        reboot_timeout: 600
      when: "'0' in snapshot_result.rc"

    - name: Wait 5 minutes before removing snapshot
      wait_for:
        timeout: 300

    - name: Delete snapshot
      shell: |
        qm delsnapshot {{ vm_id }} "{{ snapshot_name }}"
      when: "'0' in snapshot_result.rc"
      ignore_errors: true
