---
- name: Update Debian/Ubuntu system and reboot if necessary
  hosts: all
  become: yes
  tasks:
    - name: Determine OS distribution
      set_fact:
        os_family: "{{ ansible_os_family }}"

    - name: Update Debian/Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: os_family == "Debian"

    - name: Get current kernel version
      command: uname -r
      register: current_kernel
      changed_when: false

    - name: Get installed kernel versions
      command: dpkg --list | grep -E 'linux-image-[0-9]+'
      register: kernel_info
      changed_when: false
      ignore_errors: true  # Ignore error if no installed kernels are found

    - name: Set installed kernel versions fact
      set_fact:
        installed_kernels: "{{ kernel_info.stdout_lines | map('regex_replace', '^ii\\s*(.*?)\\s.*$', '\\1') | list }}"

    - name: Check if a reboot is required
      set_fact:
        reboot_required: "{{ installed_kernels | select('search', current_kernel.stdout) | list | length == 0 }}"

    - name: Reboot the system if required
      reboot:
      when: reboot_required | bool  # Default to false if not set
