---
- name: Aktualizacja Windows Server 2022
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Instalacja aktualizacji
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      register: update_result

    - name: Wyświetlanie wyników aktualizacji
      debug:
        var: update_result
